#ifndef PosixProcessFieldBit_INCLUDED
#define PosixProcessFieldBit_INCLUDED

#include "taskman/common/declaration.h"

class PosixProcessFieldBit {
public:
    DECLARE_FIELD_BIT(PID, 62);
    DECLARE_FIELD_BIT(PPID, 61);
    DECLARE_FIELD_BIT(NAME, 0);
    DECLARE_FIELD_BIT(STATE, 1);
    DECLARE_FIELD_BIT(PGRP, 2);
    DECLARE_FIELD_BIT(NICE, 3);
    DECLARE_FIELD_BIT(STARTTIME, 4);
    DECLARE_FIELD_BIT(REAL_UID, 5);
    DECLARE_FIELD_BIT(EFFECTIVE_UID, 6);
    DECLARE_FIELD_BIT(REAL_GID, 7);
    DECLARE_FIELD_BIT(EFFECTIVE_GID, 8);
    DECLARE_FIELD_BIT(REAL_USER, 9);
    DECLARE_FIELD_BIT(EFFECTIVE_USER, 10);
    DECLARE_FIELD_BIT(REAL_GROUP, 11);
    DECLARE_FIELD_BIT(EFFECTIVE_GROUP, 12);
    DECLARE_FIELD_BIT(COMMAND_LINE, 13);
};

#endif // PosixProcessFieldBit_INCLUDED
